# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GSTGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=60)),
                ('tax', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GSTServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=60)),
                ('tax', models.IntegerField()),
            ],
        ),
    ]
