# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GSTBilling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstgoods',
            name='tax',
            field=models.FloatField(),
        ),
    ]
